version: "3.9"
services:

  # # No network emulation is run
  # normal:
  #   depends_on:
  #     - daemon
  #   image: netem-client
  #   labels:
  #     com.netem.behavior: ping
  #   deploy:
  #     replicas: 1
    
  # # Higher latency, huge packet loss and duplication
  # poor:
  #   depends_on:
  #     - daemon
  #   image: netem-client
  #   labels:
  #     com.netem.behavior: ping
  #     com.netem.tc.delay: 100ms
  #     com.netem.tc.loss: 50%
  #     com.netem.tc.duplicate: 50%
  #   deploy:
  #     replicas: 1

  # # Latency ranges a lot
  # sporadic:
  #   depends_on:
  #     - daemon
  #   image: netem-client
  #   labels:
  #     com.netem.behavior: ping
  #     com.netem.tc.delay: 50ms 50ms distribution normal
  #   deploy:
  #     replicas: 1

  # # Just sleeps!
  # sleeper:
  #   depends_on:
  #     - daemon
  #   image: netem-client
  #   labels:
  #     com.netem.behavior: none
  #   deploy:
  #     replicas: 1
  
  # # Runs a client script
  # scripter:
  #   depends_on:
  #     - daemon
  #   image: netem-client
  #   labels:
  #     com.netem.behavior: script
  #   volumes:
  #     - ../scripts/:/scripts/
  #     - ../network-stats/:/network-stats/
  #     - ../data/:/data/
  #   deploy:
  #     replicas: 1

  # # No command given -- should also sleep but raise warning.
  # nothing:
  #   depends_on:
  #     - daemon
  #   image: netem-client
  #   labels: {}
  #   deploy:
  #     replicas: 1

  client:
    depends_on:
      - daemon
      - router
    image: netem-client
    networks:
      intranet:
    cap_add:
      - NET_ADMIN
    volumes:
      - ../scripts/:/scripts/
      - ../network-stats/:/network-stats/
      - ../data/:/data/
    env_file:
      - ../.env
    labels:
      com.netem.type: client
      com.netem.behavior: ping

  router:
    depends_on:
      - daemon
    image: netem-router
    networks:
      default:
        priority: 1000 # Ensure we use the eth0 interface
      intranet:
        aliases:
          - router
    cap_add:
      - NET_ADMIN
    labels:
      com.netem.type: router
      com.netem.tc.delay: 100ms

  daemon:
    image: netem-daemon
    command: python /scripts/daemon.py
    environment:
      # This host address should work for Windows and Mac. For Linux a different
      # approach is needed in order to allow Docker within Docker -- see the
      # override file.
      DOCKER_HOST: tcp://host.docker.internal:2375
    volumes:
      - ../scripts/:/scripts/
    labels:
      com.netem.type: daemon

networks:
  intranet:
