# NOTE: The Compose file takes relative paths. It will be located in the
# `/built` directory, so all mount paths should be prefixed by `../` to access
# the root project directory.

client:
  depends_on:
    - daemon
    - router
  image: iperf 
  networks: []
  cap_add:
    - NET_ADMIN
  volumes:
    - ../scripts/:/scripts/
  env_file: []
  labels:
    com.dane.type: client
    com.dane.behavior: BEHAVIOR_VALUE

lossem:
  image: lossem
  cap_add:
    - NET_ADMIN
  depends_on:
    - daemon
    - router
  networks:
    CLIENT_NETWORK:
      aliases:
        - CLIENT_NETWORK_ALIAS
    ROUTER_NETWORK:
      aliases:
        - ROUTER_NETWORK_ALIAS
  labels:
    com.dane.type: lossem
    com.dane.lossem.latency: LATENCY_VALUE
    com.dane.lossem.loss: BANDWIDTH_VALUE
  volumes:
    - ../scripts:/scripts/

router:
  depends_on:
    - daemon
  image: iperf 
  networks:
    default:
      aliases: []
  cap_add:
    - NET_ADMIN
  volumes:
    - ../scripts/:/scripts/
  labels:
    com.dane.type: router

network: {}
